# Generated by Django 6.0.2 on 2026-03-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember_created_at_projectmember_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='name',
        ),
    ]
