### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

###
POST https://localhost:8080/api/token HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}