services:
  - type: web
    name: esmt-tasks
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://esmt-tasks.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://esmt-tasks.onrender.com"
