# Generated by Django 6.0.3 on 2026-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('deadline', 'Date limite'), ('assignement', 'Tâche'), ('prime', 'Prime'), ('message', 'Message')], default='deadline', max_length=20),
        ),
    ]
