# Generated by Django 6.0.3 on 2026-03-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_message_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
