# Generated by Django 6.0.3 on 2026-03-06 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to_task_deadline_task_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date de validation par le propriétaire du projet.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
