# Generated by Django 6.0.3 on 2026-03-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_add_validated_at_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notified_1_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_48_hours',
            field=models.BooleanField(default=False),
        ),
    ]
